name: 'Create release'
description: > 
  Create a GitHub release with the provided artifacts, and generates release notes 
  based on the commits between the latest and the target branch
author: 'FBITN'
inputs:
  name:
    description: >
      The name of the release. It's a common practice to use the version number
      A new tag will be created using the release name.
      An error will be thrown if a tag wit the same name already exists
    required: true
  target:
    description: 'The branch or tag to create the release from'
    required: true
  artifacts:
    description: 'A set of paths to the artifacts to upload to the release'
    required: true
  artifact-name:
    description: 'The name of the generated zip file that will contain all the release artifacts'
    default: 'artifact'
  prerelease:
    description: 'Flag to mark the release as a prerelease or not, default is true.'
    default: 'true'
    required: false
  artifacts-directory:
    description: 'The directory where the artifacts are located. Default is the root of the work-space.'
    default: './'
    required: false
runs:
  using: "composite"
  steps:
    - name: Zipping artifacts
      run: |
        echo "Zipping artifacts into the ${{ inputs.artifact-name }}.zip file"
        zip -r ./${{ inputs.artifact-name }}.zip ${{ inputs.artifacts }}
      shell: bash
      working-directory: ${{ inputs.artifacts-directory }}
    - name: Creating a GitHub release
      run: ${{ github.action_path }}/release.sh ${{ inputs.name }} ${{ inputs.target }} ${{ inputs.artifact-name }}.zip ${{ inputs.prerelease }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      working-directory: ${{ inputs.artifacts-directory }}
