name: 'Create release'
description: 'Create a GitHub release'
inputs:
  name:
    description: 'The name of the release'
    required: true
  version:
    description: 'The version of the release'
    required: true
  target:
    description: 'The branch or tag to create the release from'
    required: true
  artifacts:
    description: 'A set of paths to the artifacts to upload to the release'
    required: true
  prerelease:
    description: 'Flag to mark the release as a prerelease or not, default is true.'
    default: 'true'
    required: false
runs:
  using: "composite"
  steps:
    - name: Zipping artifacts
      run: |
        echo "Zipping artifacts"
        zip -r ./${{ inputs.name }}.zip ${{ inputs.artifacts }}
      shell: bash
    - name: Creating a GitHub release marked as prerelease
      run: ${{ github.action_path }}/prerelease.sh ${{ inputs.version }} ${{ inputs.target }} ${{ inputs.name }}.zip ${{ inputs.prerelease }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}