name: 'Download release'
description: 'Download artifacts from a GitHub release'
author: 'FBITN'
inputs:
  name:
    description: 'The name of the release tag to download the artifacts from'
    required: true
  repository:
    description: 'The repository to download the release from, default (current repository)'
    required: false
    default: ${{ github.repository }}
  directory:
    description: 'The directory to download files into, default (.)'
    required: false
    default: '.'
  pattern:
    description: 'Glob pattern to match the assets to be downloaded from the release'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      run: echo "###### Repository:" ${{ inputs.repository }}
      shell: bash
    - name: Downloading the release
      run: ${{ github.action_path }}/download.sh ${{ inputs.name }} ${{ inputs.repository }} ${{ inputs.directory }} ${{ inputs.pattern }} 
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}